variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - staging
  - prod


prod-job:
  image: python:3.6
  stage: prod
  script:
    - pip install -r requirements.txt
    - chmod +x unit-tests.sh
    - mkdir logs
    - ./unit-tests.sh
  environment:
    name: production
    url: https://counties.farmdrive.co.ke/demo
  after_script:
    - echo "$PROD_SERVER_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem
    - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$PROD_SERVER_IP "mkdir -p ~/county-wards"
    - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$PROD_SERVER_IP "rm -rf ~/county-wards/migrations"
    - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$PROD_SERVER_IP "rm -rf ~/county-wards/app"
    - scp -i key.pem -r Dockerfile docker-compose-prod.yml requirements.txt wsgi.py settings.py entrypoint.sh app/ ubuntu@$PROD_SERVER_IP:~/county-wards
    - ssh -i key.pem ubuntu@$PROD_SERVER_IP "cd ~/county-wards; mv docker-compose-prod.yml docker-compose.yml"
    - ssh -i key.pem ubuntu@$PROD_SERVER_IP "cd ~/county-wards; export DEPLOYED=True; docker-compose up -d --build"
  only:
    - master


staging-job:
  image: python:3.6
  stage: staging
  script:
    - pip install -r requirements.txt
    - chmod +x unit-tests.sh
    - mkdir logs
    - ./unit-tests.sh
  environment:
    name: staging
    url: https://staging.counties.farmdrive.co.ke/demo
  after_script:
    - echo "$STAGING_SERVER_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem
    - ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$STAGING_SERVER_IP "mkdir -p ~/county-wards-staging"
    - ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$STAGING_SERVER_IP "rm -rf ~/county-wards-staging/migrations"
    - ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@$STAGING_SERVER_IP "rm -rf ~/county-wards-staging/app"
    - scp -i key.pem -r Dockerfile docker-compose.yml requirements.txt wsgi.py settings.py entrypoint.sh app/ ec2-user@$STAGING_SERVER_IP:~/county-wards-staging
    - ssh -i key.pem ec2-user@$STAGING_SERVER_IP "cd ~/county-wards-staging; export DEPLOYED=True; docker-compose up -d --build"
  only:
    - staging