version: '3'

services:
  county-wards:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: county-wards
    ports:
      - 8004:8004
    environment:
      - APP_ENVIRONMENT=development

